### ISSUE TITLE
1.2.0.0 on Mac OS not working

### ISSUE THREAD

**Issue by jamesvanmil** [Nornec/Midinous-Issues#59] opened 2024-05-06 12:51 UTC
Worked w/o issue on 11.x, after the update, grid isn't rendering and unable to place any nodes:

<img width="1268" alt="Screen Shot 2024-05-06 at 8 48 16 AM" src="https://github.com/Nornec/Midinous-Issues/assets/2651187/f1e7228f-50cd-4032-9331-06a90b950673">

**Comment by Nornec** [comment] 2024-05-06 14:36
Please delete your settings file. That should clear this up. Still trying to find a root cause. Seems to be really inconsistent with who does and doesn't get the problem.

-Jae (they/them)

**Comment by Joe-Gigs** [comment] 2024-05-06 16:02
What is the name of the file I should delete? Also having this issue on Mac OS.

**Comment by jamesvanmil** [comment] 2024-05-06 16:58
@Joe-Gigs  `/Users/YOURNAME/.local/share/Midinous/user/settings.json`

Deleting this fixed the issue for me on restart - thanks!

**Comment by Joe-Gigs** [comment] 2024-05-06 17:09
Thank you!

**Comment by Nornec** [comment] 2024-05-07 20:40
Fixed in 1.2.0.1

**Closed by Nornec** 2024-05-07 20:40 UTC
Labels: bug
