### ISSUE TITLE
Note Property Fails to Correctly Update from MIDI Input Under Specific Circumstances

### ISSUE THREAD

**Issue by InnocuousChaos** [Nornec/Midinous-Issues#49] opened 2023-07-22 00:45 UTC
Reproduction Steps 1:
- Create New project
- Place note point
- Select the point
- Open either the Octave or Note drop down
- Close the window by clicking anywhere, or by selecting a value from the drop down
- Press a button on the MIDI Input device
- The text box value changes to match the input note, but the drop downs do not change. Deselecting then selecting the point, or hitting play, reveals the value didn't actually change to match the MIDI input.

Reproduction Steps 2:
- Create New project
- Place note point
- Select the point
- Click the note text box
- The Note value is unresponsive to MIDI input until the cursor is no longer in the Text Box

**Comment by Nornec** [comment] 2023-07-27 22:00
Looks like step 1 is a problem with how values are getting set and in what order. scenario 2 is expected behavior because if your cursor is in the text box, the thought is that you are in the process of changing the value to something you want and you would not want that getting overwritten. I will investigate the first scenario.

**Comment by Nornec** [comment] 2023-11-24 02:56
Possibly fixed in 1.1.7.0. After the update rolls out, feel free to re-open.

**Closed by Nornec** 2023-11-24 02:56 UTC
Labels: bug, expected behavior
